const pokeData = [
  {
    "_id": "5cef3501ef6005a77cd4fdd0",
    "pokemon": "pichu",
    "id": 187,
    "species_id": 172,
    "height": 3,
    "weight": 20,
    "base_experience": 41,
    "type_1": "electric",
    "type_2": "NA",
    "attack": 40,
    "defense": 15,
    "hp": 20,
    "special_attack": 35,
    "special_defense": 35,
    "speed": 60,
    "ability_1": "static",
    "ability_2": "NA",
    "ability_hidden": "lightning-rod",
    "color_1": "#F8D030",
    "color_2": "NA",
    "color_f": "NA",
    "egg_group_1": "no-eggs",
    "egg_group_2": "NA",
    "url_image": "http://assets.pokemon.com/assets/cms2/img/pokedex/full/172.png",
    "generation_id": 2,
    "evolves_from_species_id": "NA",
    "evolution_chain_id": 10,
    "shape_id": 8,
    "shape": "quadruped",
    "pokebase": "pichu",
    "pokedex": "http://www.pokemon.com/us/pokedex/pichu"
  },
  {
    "_id": "5cef3501ef6005a77cd4fd16",
    "pokemon": "venusaur",
    "id": 3,
    "species_id": 3,
    "height": 20,
    "weight": 1000,
    "base_experience": 236,
    "type_1": "grass",
    "type_2": "poison",
    "attack": 82,
    "defense": 83,
    "hp": 80,
    "special_attack": 100,
    "special_defense": 100,
    "speed": 80,
    "ability_1": "overgrow",
    "ability_2": "NA",
    "ability_hidden": "chlorophyll",
    "color_1": "#78C850",
    "color_2": "#A040A0",
    "color_f": "#81A763",
    "egg_group_1": "monster",
    "egg_group_2": "plant",
    "url_image": "http://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png",
    "generation_id": 1,
    "evolves_from_species_id": "2",
    "evolution_chain_id": 1,
    "shape_id": 8,
    "shape": "quadruped",
    "pokebase": "venusaur",
    "pokedex": "http://www.pokemon.com/us/pokedex/venusaur"
    }
]

export default pokeData;